language: python

matrix:
    include:
        - python: 2.7
          env: {TOX_ENV: py27, COVERAGE: 1}
#        - python: 2.7
#          env: {TOX_ENV: docs}
        - python: 2.7
          env: {TOX_ENV: flake8}

install:
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install -qq bash-completion swig
    - travis_retry pip install tox sphinx
    - travis_retry sudo apt-get install git libcairo2-dev libgtk2.0-dev libglib2.0-dev libtool libpango1.0-dev libatk1.0-dev libffi-dev libpq-dev libmysqlclient-dev
    - "[ ! -z $COVERAGE ] && pip install coveralls || true"
    - pip install --allow-all-external -r requirements.txt
  # Environment setup
    - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
    - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
  # PyCairo
    - wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
    - tar xf py2cairo-1.10.0.tar.bz2
    - cd py2cairo-1.10.0
    - ./waf configure --prefix=$VIRT_ROOT > /dev/null
    - ./waf build > /dev/null
    - ./waf install > /dev/null
    - cd ..
  # PyGobject
    - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
    - tar xf pygobject-2.28.6.tar.bz2
    - cd pygobject-2.28.6
    - ./configure --prefix=$VIRT_ROOT --disable-introspection > /dev/null
    - make > /dev/null
    - make install > /dev/null
    - cd ..
  # PyGtk
    - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
    - tar xf pygtk-2.24.0.tar.bz2
    - cd pygtk-2.24.0
    - ./configure --prefix=$VIRT_ROOT > /dev/null
    - make > /dev/null
    - make install > /dev/null
    - cd ..
    # gstreamer
    - travis_retry sudo apt-get -qq install python-gst0.10 python-gst0.10-dev gstreamer0.10-plugins-good
    - python -c 'import pygst'
    - python -c 'import gst'
    - travis_retry sudo apt-get -qq install gstreamer0.10-plugins-bad gstreamer0.10-plugins-ugly
    - travis_retry sudo apt-get -qq install gstreamer0.10-pulseaudio
    - travis_retry sudo apt-get -qq install gstreamer0.10-alsa

#install: pip install --allow-all-external -r requirements.txt

script: tox -e $TOX_ENV

# Only report coverage for one version.
after_success:
    - "[ ! -z $COVERAGE ] && coveralls || true"

#script: python tests/test_scarlett.py unit
