language: python
matrix:
  include:
  - python: 2.7
    env:
      TOX_ENV: py27
      COVERAGE: 1
      GSTREAMER: 0.1
      TEST_PEP8: 1
  - python: 2.7
    env:
      TOX_ENV: flake8
services:
- redis-server
install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sh -c "echo -e \"\e[31mGSTREAMER VERSION $GSTREAMER\e[39;\""

# 5.24.2015 START
- travis_retry sudo add-apt-repository -y ppa:gstreamer-developers/ppa
# 5.24.2015 STOP

- travis_retry sudo apt-get update
- travis_retry sudo apt-get install -qq bash-completion swig
- travis_retry pip install tox sphinx nose

# 5.24.2015 START
- travis_retry sudo apt-get install -qq build-essential autotools-dev automake autoconf libtool autopoint libxml2-dev zlib1g-dev libglib2.0-dev pkg-config bison flex python git gtk-doc-tools libasound2-dev libgudev-1.0-dev libxt-dev libvorbis-dev libcdparanoia-dev libpango1.0-dev libtheora-dev libvisual-0.4-dev iso-codes libgtk-3-dev libraw1394-dev libiec61883-dev libavc1394-dev libv4l-dev libcairo2-dev libcaca-dev libspeex-dev libpng-dev libshout3-dev libjpeg-dev libaa1-dev libflac-dev libdv4-dev libtag1-dev libwavpack-dev libpulse-dev libsoup2.4-dev libbz2-dev libcdaudio-dev libdc1394-22-dev ladspa-sdk libass-dev libcurl4-gnutls-dev libdca-dev libdirac-dev libdvdnav-dev libexempi-dev libexif-dev libfaad-dev libgme-dev libgsm1-dev libiptcdata0-dev libkate-dev libmimic-dev libmms-dev libmodplug-dev libmpcdec-dev libofa0-dev libopus-dev librsvg2-dev librtmp-dev libschroedinger-dev libslv2-dev libsndfile1-dev libsoundtouch-dev libspandsp-dev libx11-dev libxvidcore-dev libzbar-dev libzvbi-dev liba52-0.7.4-dev libcdio-dev libdvdread-dev libmad0-dev libmp3lame-dev libmpeg2-4-dev libopencore-amrnb-dev libopencore-amrwb-dev libsidplay1-dev libtwolame-dev libx264-dev
- travis_retry sudo apt-get install -qq libgirepository1.0-dev gstreamer1.0-plugins-good gir1.2-clutter-1.0 gir1.2-clutter-gst-1.0 gir1.2-gtkclutter-1.0 gir1.2-gtksource-3.0 gir1.2-vte-2.90 gir1.2-webkit-1.0 gir1.2-webkit-3.0
- travis_retry sudo apt-get install -qq git libcairo2-dev libgtk2.0-dev libglib2.0-dev libtool libpango1.0-dev libatk1.0-dev libffi-dev libpq-dev libmysqlclient-dev
- travis_retry sudo apt-get install -qq libglib2.0-*
# 5.24.2015 STOP

- travis_retry sudo apt-get install git libcairo2-dev libgtk2.0-dev libglib2.0-dev
  libtool libpango1.0-dev libatk1.0-dev libffi-dev libpq-dev libmysqlclient-dev
- export MAIN_DIR=$(pwd)
- export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
- export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
- export SCARLETT_CONFIG=$MAIN_DIR/tests/fixtures/.scarlett
- export SCARLETT_HMM=$MAIN_DIR/tests/fixtures/model/hmm/en_US/hub4wsj_sc_8k
- export SCARLETT_LM=$MAIN_DIR/tests/fixtures/lm/1602.lm
- export SCARLETT_DICT=$MAIN_DIR/tests/fixtures/dict/1602.dic

# install py2cairo
- wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
- tar xf py2cairo-1.10.0.tar.bz2
- cd py2cairo-1.10.0
- "./waf configure --prefix=$VIRT_ROOT > /dev/null"
- "./waf build > /dev/null"
- "./waf install > /dev/null"
- cd ..

#### OLD # # install pygobject
#### OLD # - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
#### OLD # - tar xf pygobject-2.28.6.tar.bz2
#### OLD # - cd pygobject-2.28.6
#### OLD # - "./configure --prefix=$VIRT_ROOT --disable-introspection > /dev/null"
#### OLD # - make > /dev/null
#### OLD # - make install > /dev/null
#### OLD # - cd ..

# Install the latest version of glib (2.32.4 is required)
# Install glib
- wget http://ftp.acc.umu.se/pub/gnome/sources/glib/2.32/glib-2.32.4.tar.xz
- tar xvf glib-2.32.4.tar.xz
- cd glib-2.32.4
- "./configure --prefix=$VIRT_ROOT > /dev/null"
- make > /dev/null
- make install > /dev/null
- cd ..
- sudo apt-get install -qq libtheora-dev libogg-dev libvorbis-dev  libasound2-dev libjack-dev

#### DISABLED # # install pygtk
#### DISABLED # - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
#### DISABLED # - tar xf pygtk-2.24.0.tar.bz2
#### DISABLED # - cd pygtk-2.24.0
#### DISABLED # - "./configure --prefix=$VIRT_ROOT > /dev/null"
#### DISABLED # - make > /dev/null
#### DISABLED # - make install > /dev/null
#### DISABLED # - cd ..

# installing more package dependencies
- travis_retry sudo apt-get -qq install git build-essential automake libtool itstool
  gtk-doc-tools gnome-common gnome-doc-utils yasm flex bison
- travis_retry sudo apt-get -qq install python-gst0.10 python-gst0.10-dev gstreamer0.10-plugins-good
- travis_retry sudo apt-get -qq install gstreamer0.10-ffmpeg gstreamer-tools gstreamer0.10-alsa
  gstreamer0.10-nice gstreamer0.10-plugins-good gstreamer0.10-plugins-bad gstreamer0.10-plugins-ugly
  gstreamer0.10-tools libgstreamer-plugins-bad0.10-0 libgstreamer-plugins-bad0.10-dev
  libgstreamer-plugins-base0.10-0 libgstreamer-plugins-base0.10-dev libgstreamer0.10-0
  libgstreamer0.10-0-dbg libgstreamer0.10-cil-dev libgstreamer0.10-dev libgstrtspserver-0.10-0
  libgstrtspserver-0.10-dev libnice-dev
- travis_retry sudo apt-get -qq install gstreamer0.10-plugins-bad gstreamer0.10-plugins-ugly
- travis_retry sudo apt-get -qq install gstreamer0.10-pulseaudio
- travis_retry sudo apt-get -qq install gstreamer0.10-alsa
- travis_retry sudo apt-get -qq install pavucontrol gstreamer0.10-pulseaudio pulseaudio
- travis_retry sudo apt-get -qq install gstreamer0.10-pulseaudio libao4 libasound2-plugins
  libgconfmm-2.6-1c2 libglademm-2.4-1c2a libpulse-dev libpulse-mainloop-glib0 libpulse-mainloop-glib0-dbg
  libpulse0 libpulse0-dbg libsox-fmt-pulse paman paprefs pavucontrol pavumeter pulseaudio
  pulseaudio-dbg pulseaudio-esound-compat pulseaudio-esound-compat-dbg pulseaudio-module-bluetooth
  pulseaudio-module-gconf pulseaudio-module-jack pulseaudio-module-lirc pulseaudio-module-lirc-dbg
  pulseaudio-module-x11 pulseaudio-module-zeroconf pulseaudio-module-zeroconf-dbg
  pulseaudio-utils
- travis_retry sudo apt-get -qq install bison
- travis_retry sudo apt-get -qq install autoconf automake bison build-essential libasound2-dev
  libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libtool python-gst0.10 python-pyside
  python-gst0.10 python-gst0.10-dbg python-gst0.10-dev python-gst0.10-rtsp python-iplib
  python-simplejson
- travis_retry sudo apt-get -qq install python-gst0.10 python-gst0.10-dbg python-gst0.10-dev
  python-gst0.10-rtsp python-pip python-setuptools python-gtk2 python-yaml python-yaml-dbg
- travis_retry sudo apt-get -qq install python2.7-dev
- travis_retry sudo apt-get -qq install bison

# install gstreamer-1.0
- travis_retry sudo apt-get -qq install gstreamer1.0* libgstreamer1.0*
#- travis_retry sudo apt-get -qq install python-gst1.0 python-gst1.0-dbg python-gst1.0-dev python-gst1.0-rtsp python-pip python-setuptools
- travis_retry sudo apt-get install -qq libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
- travis_retry sudo apt-get install -qq libusb-1.0

# OLD # # set env variables
# OLD # - export LD_LIBRARY_PATH=$VIRT_ROOT/lib
# OLD # - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
# OLD # - export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-0.10

# OLD # install gst-python
# OLD # - wget http://gstreamer.freedesktop.org/src/gst-python/gst-python-0.10.22.tar.bz2
# OLD # - tar xf gst-python-0.10.22.tar.bz2
# OLD # - cd gst-python-0.10.22
# OLD # - "./configure --prefix=$VIRT_ROOT"
# OLD # - make > /dev/null
# OLD # - make install > /dev/null
# OLD # - cd ..
# OLD # - python -c 'import pygst'
# OLD # - python -c 'import gst'

# install gst-python
- wget http://gstreamer.freedesktop.org/src/gst-python/gst-python-1.2.1.tar.bz2
- tar xf gst-python-1.2.1.tar.bz2
- cd gst-python-1.2.1
- #./configure --prefix=$VIRT_ROOT PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$VIRT_ROOT/lib/pkgconfig
- "./configure --prefix=$VIRT_ROOT > /dev/null"
- make > /dev/null
- make install > /dev/null
- cd ..

# - travis_retry git clone https://github.com/bossjones/bossjones-ruamel-venvgtk.git
# - cd bossjones-ruamel-venvgtk
# - python setup.py install
# - cd ..

# This package is intended to be included in e.g. a tox.ini file for testing of packages that rely on gtk2.0. under Linux.
- pip install ruamel.venvgtk

# import test
- python -c 'from gi.repository import Gtk; print Gtk'
- python -c 'import gst'

# set env variables
- export LD_LIBRARY_PATH=$VIRT_ROOT/lib
- export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
- export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-0.10

- wget http://downloads.sourceforge.net/project/cmusphinx/sphinxbase/0.8/sphinxbase-0.8.tar.gz
- tar -zxf sphinxbase-0.8.tar.gz
- cd sphinxbase-0.8
- "./configure"
- make
- sudo make install
- cd ..
- travis_retry git clone https://github.com/bossjones/bossjones-pocketsphinx.git
- cd bossjones-pocketsphinx
- "./configure"
- make
- sudo make install
- cd ..
- sudo ldconfig
- pip install -r requirements.txt --use-mirrors
- pip install -r requirements_plugins.txt --use-mirrors
- pip install -r requirements_dev.txt --use-mirrors
- python setup.py install
- "[ ! -z $COVERAGE ] && pip install coveralls || true"
script: if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg
  scarlett;fi; tox -e ${TOX_ENV}
after_success:
- "[ ! -z $COVERAGE ] && coveralls || true"
notifications:
  slack:
    secure: WwqeVdCpCF8UNnZURer9niMubvLYrANcUoZfl3oEzWtkVKSxZgL4dzkuzi8o85U9kM8rwlBZ/OK7Rit7JA6GcvmIJWCQdxqZPnk3yo0T1HqOtBAgyIlqOJXqyKtYp8t7+wfQ402pF1BAUDyi/HlqyKIx2jeGzOYwH7oHQW9mK6Y=
