language: python

matrix:
    include:
        - python: 2.7
          env: {TOX_ENV: py27, COVERAGE: 1}
        - python: 2.7
          env: {TOX_ENV: docs}
        - python: 2.7
          env: {TOX_ENV: flake8}

install:
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install -qq bash-completion swig
    - travis_retry pip install tox sphinx
    - "[ ! -z $COVERAGE ] && pip install coveralls || true"
    - pip install --allow-all-external -r requirements.txt

#install: pip install --allow-all-external -r requirements.txt

script: tox -e $TOX_ENV

# Only report coverage for one version.
after_success:
    - "[ ! -z $COVERAGE ] && coveralls || true"

#script: python tests/test_scarlett.py unit
